codecov:
  max_report_age: 1
  require_ci_to_pass: false
  token: bacfe94a-4168-4328-88a6-9584a651cd1d

comment:
  behavior: default
  layout: reach, diff, flags, files
  require_changes: true

coverage:
  precision: 2
  range:
    - 50.0
    - 100.0
  round: down
  status:
    patch:
      default:
        informational: true
        target: auto
        threshold: 5
    project:
      default:
        informational: true
        target: auto
        threshold: 5

ignore:
  - tests/**
  - docs/**
  - "**/build/**"
  - "**/_deps/**"
