# CMake generated Testfile for 
# Source directory: /home/runner/work/BlockChainDrachma/BlockChainDrachma
# Build directory: /home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/schnorr_vectors_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/difficulty_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/pow_check_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/mempool_stress_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/wallet_sign_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/p2p_dos_sim_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/p2p_multinode_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/bloom_filter_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/rpc_server_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/regtest_mode_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/regtest_private_chain_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/crosschain_bridge_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/sidechain_evm_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/nft_precompile_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/nft_market_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/nft_ui_helpers_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/peg_bridge_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/sidechain_wasm_execution_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/stratum_client_test[1]_include.cmake")
add_test(schnorr_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/schnorr_test")
set_tests_properties(schnorr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;231;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(merkle_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/merkle_test")
set_tests_properties(merkle_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;239;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(supply_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/supply_test")
set_tests_properties(supply_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;243;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(asset_policy_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/asset_policy_test")
set_tests_properties(asset_policy_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;246;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(retarget_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/retarget_test")
set_tests_properties(retarget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;250;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(difficulty_adjust_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/difficulty_adjust_test")
set_tests_properties(difficulty_adjust_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;262;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(validation_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/validation_tests")
set_tests_properties(validation_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;266;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(fork_resolution_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/fork_resolution_test")
set_tests_properties(fork_resolution_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;270;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(chainstate_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/chainstate_tests")
set_tests_properties(chainstate_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;274;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(mempool_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/mempool_tests")
set_tests_properties(mempool_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;278;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(block_validation_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/block_validation_tests")
set_tests_properties(block_validation_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;290;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(p2p_integration_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/p2p_integration_test")
set_tests_properties(p2p_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;294;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(anti_dos_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/anti_dos_tests")
set_tests_properties(anti_dos_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;310;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(attacks_sim "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/attacks_sim")
set_tests_properties(attacks_sim PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;314;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
subdirs("_deps/leveldb-build")
subdirs("_deps/googletest-build")
