if(EXISTS "/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/nft_market_test[1]_tests.cmake")
  include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/build-cov/nft_market_test[1]_tests.cmake")
else()
  add_test(nft_market_test_NOT_BUILT nft_market_test_NOT_BUILT)
endif()
